# Generated by Django 3.0.8 on 2021-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullorder',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
