# Generated by Django 3.0.8 on 2021-03-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('prescription', models.CharField(default='', max_length=255)),
                ('prescriptionImage', models.ImageField(upload_to='images/pres/')),
            ],
        ),
    ]
