# Generated by Django 3.0.8 on 2021-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullorder',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
