# Generated by Django 3.0.8 on 2021-03-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type_user',
        ),
    ]
